services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_technologies_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
